---
- name: install packages
  with_items: "{{ ldap_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart ldap

- name: enable slapd service
  template:
    src: slapd.j2
    dest: /etc/rc.conf.d/slapd

- name: keep the config
  file:
    path: /var/db/openldap-data/.keep
    state: directory

- name: install opendkim schema
  template:
    src: opendkim.schema.j2
    dest: /usr/local/etc/openldap/schema/opendkim.schema
  notify:
    - restart ldap

- name: configure ldap server
  with_items: "{{ ldap_templates }}"
  template:
    src: "{{ item.filename }}.tpl"
    dest: "{{ item.destination }}/{{ item.filename }}"
  notify:
    - restart ldap

- name: check if slapd-secret.conf exists
  stat:
    path: /usr/local/etc/openldap/slapd-secret.conf
  register: secret_result

- name: create slapd-secret.conf if it does not exists
  template:
    src: slapd-secret.conf.j2
    dest: /usr/local/etc/openldap/slapd-secret.conf
    mode: 0600
    owner: ldap
    group: ldap
  when: secret_result.stat.exists == False
  notify:
    - restart ldap
